apiVersion: v1
kind: Secret
metadata:
  name: {{ include "video-understanding.fullname" . }}-secret
  labels:
    {{- include "video-understanding.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_URL: {{ .Values.secrets.postgresUrl | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  HUGGINGFACE_TOKEN: {{ .Values.secrets.huggingfaceToken | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
